apiVersion: v2
name: operator-for-redis
type: application
version: 0.0.0  # Overridden by release workflow
description: Operator for creating and managing Redis clusters
maintainers:
  - name: tomashibm  # Tomash Sidei
  - name: cin        # Craig Ingram
  - name: antonioua  # Anton Kuznietsov
  - name: kscharm    # Kenny Scharm
